In [6]:
import tensorflow as tf
mat0 = tf.constant([[0,0,0],[0,0,0]])
mat1 = tf.zeros([2,3])# 空矩阵
mat2 = tf.ones([2,3])# 全1矩阵
mat3 = tf.fill([2,3],15)# 全15矩阵
with tf.Session() as sess:
    print(sess.run(mat0))
    print(sess.run(mat1))
    print(sess.run(mat2))
    print(sess.run(mat3))

[[0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[15 15 15]
 [15 15 15]]


In [9]:
import tensorflow as tf
mat0 = tf.constant([[2],[3],[4]])
mat1 = tf.zeros_like(mat0)
mat2 = tf.linspace(0.0,2.0,11)
mat3 = tf.random_uniform([2,3],-1,2)
with tf.Session() as sess:
    print(sess.run(mat1))
    print(sess.run(mat2))
    print(sess.run(mat3))


[[0]
 [0]
 [0]]
[0.        0.2       0.4       0.6       0.8       1.        1.2
 1.4       1.6       1.8000001 2.       ]
[[-0.59988487  0.4865049  -0.8445982 ]
 [ 0.9893193  -0.15383422  1.2831893 ]]
